apiVersion: v1
kind: ConfigMap
metadata:
  name: steven-alert-rules
data:
  alert-rules.yml: |
    groups:
    - name: URLStatus
      rules:
      - alert: WebsiteDown
        expr: url_up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Website is DOWN"
          description: "The monitored URL is not responding."
