apiVersion: v1
kind: ConfigMap
metadata:
  name: steven-alertmanager-config
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m

    route:
      receiver: "default-receiver"

    receivers:
      - name: "default-receiver"
        webhook_configs:
          - url: "http://steven-monitoring-app:5000/"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: steven-alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steven-alertmanager
  template:
    metadata:
      labels:
        app: steven-alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager
          args:
            - "--config.file=/etc/alertmanager/alertmanager.yml"
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager/alertmanager.yml
              subPath: alertmanager.yml
      volumes:
        - name: alertmanager-config
          configMap:
            name: steven-alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: steven-alertmanager
spec:
  type: ClusterIP
  selector:
    app: steven-alertmanager
  ports:
    - port: 9093
      targetPort: 9093
