apiVersion: v1
kind: ConfigMap
metadata:
  name: steven-alertmanager-config
  labels:
    app: steven-alertmanager
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: "email-notifications"

    receivers:
      - name: "email-notifications"
        email_configs:
          - to: "TU_CORREO@gmail.com"
            from: "TU_CORREO@gmail.com"
            smarthost: "smtp.gmail.com:587"
            auth_username: "TU_CORREO@gmail.com"
            auth_identity: "TU_CORREO@gmail.com"
            auth_password: "AQU√ç-TU-APP-PASSWORD"
            require_tls: true
