apiVersion: v1
kind: ConfigMap
metadata:
  name: steven-prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "steven-monitoring-app"
        static_configs:
          - targets: ["steven-app-service:5000"]

    rule_files:
      - /etc/prometheus/alert-rules.yml

    alerting:
      alertmanagers:
        - static_configs:
            - targets: ["steven-alertmanager:9093"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: steven-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: steven-prometheus
  template:
    metadata:
      labels:
        app: steven-prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: prometheus-rules
              mountPath: /etc/prometheus/alert-rules.yml
              subPath: alert-rules.yml
      volumes:
        - name: prometheus-config
          configMap:
            name: steven-prometheus-config
        - name: prometheus-rules
          configMap:
            name: steven-alert-rules
---
apiVersion: v1
kind: Service
metadata:
  name: steven-prometheus
spec:
  type: ClusterIP
  selector:
    app: steven-prometheus
  ports:
    - port: 9090
      targetPort: 9090
